# -*- coding: utf-8 -*-
"""bronze_kpi_weekly_table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JULDfouwqT8AIKCggB4VFChS5Go2HNow
"""

import pandas as pd
import numpy as np

# Weekly file
weekly = pd.read_excel('/content/Weekly 202201-202412(1).xlsx')

# Aug actuals file
aug = pd.read_excel('/content/Aug actuals with DOM (1).xlsx')

weekly.shape, aug.shape

"""# Lane Harmonization"""

# Lane mapping dictionary
lane_map = {
    "EU": "Europe",
    "AS": "APAC",
    "ME": "MEISA",
    "NA": "Americas",
    "LA": "Americas"}

# apply mapping to weekly file
weekly['Dest_Lane'] = weekly['Dest_Lane'].replace(lane_map)

# apply lane recovery rule to aug file
aug.loc[(aug['Lane_'].isna()) & (aug['Lane']=='Americas'), 'Lane_'] = 'LA'

# Harmonize Lane_
aug['Dest_Lane'] = aug['Lane_'].replace(lane_map)

"""# Unit Standardization"""

# weekly files
weekly['aPounds'] = pd.to_numeric(weekly['aPounds'], errors='coerce')
weekly['Pounds'] = pd.to_numeric(weekly['Pounds'], errors='coerce')
weekly['PACKS'] = pd.to_numeric(weekly['PACKS'], errors='coerce')
weekly['Shipments'] = pd.to_numeric(weekly['Shipments'], errors='coerce')

# aug files
aug = aug.rename(columns={'Packs': 'PACKS', 'aLbs': 'aPounds'})

# convert to numeric
aug['aPounds'] = pd.to_numeric(aug['aPounds'], errors='coerce')
aug['PACKS'] = pd.to_numeric(aug['PACKS'], errors='coerce')
aug['Shipments'] = pd.to_numeric(aug['Shipments'], errors='coerce')

# adding kg column
weekly['aKg'] = weekly['aPounds'] * 0.453592
aug['aKg'] = aug['aPounds'] * 0.453592

"""# Creating Canonical Bronze Table"""

weekly['ship_date'] = pd.NaT # weekly aggregated

weekly_bronze = weekly[[
    "ship_date",
    "FY",
    "WeekNbr",
    "Orig_Ctry",
    "ORIG_RAMP",
    "Business_Region",
    "Dest_Lane",
    "Product_Code",
    "PACKS",
    "Shipments",
    "aPounds"]]

# Transform aug file
aug["ship_date"] = pd.to_datetime(aug["ShipDate"], errors="coerce")
aug["Year"] = aug["yyyymm"].astype(str).str[:4]
aug["FY"] = "FY" + aug["Year"].str[-2:]
aug["Product_Code"] = aug["Product"]

aug_bronze = aug[[
    "ship_date",
    "FY",
    "WeekNbr",
    "Orig_Ctry",
    "ORIG_RAMP",
    "Business_Region",
    "Dest_Lane",
    "Product_Code",
    "PACKS",
    "Shipments",
    "aPounds"]]

"""# Combining files"""

bronze_kpi = pd.concat([weekly_bronze, aug_bronze], ignore_index=True)

# fill null measures
bronze_kpi[["PACKS", "Shipments", "aPounds"]] = bronze_kpi[["PACKS", "Shipments", "aPounds"]].fillna(0)

bronze_kpi = bronze_kpi[[
    "ship_date",
    "FY",
    "WeekNbr",
    "Orig_Ctry",
    "ORIG_RAMP",
    "Business_Region",
    "Dest_Lane",
    "Product_Code",
    "PACKS",
    "Shipments",
    "aPounds"]]

"""# Time coverage + Continuity grid"""

# Unique Keys
keys = bronze_kpi[["ORIG_RAMP", "Dest_Lane", "Product_Code"]].drop_duplicates()

# Unique time combination
time_dim = bronze_kpi[["FY", "WeekNbr"]].drop_duplicates()

# Cross join
keys["key"] = 1
time_dim["key"] = 1

full_grid = keys.merge(time_dim, on="key").drop("key", axis=1)

# Merge with Bronze
bronze_full = full_grid.merge(bronze_kpi, on=["ORIG_RAMP", "Dest_Lane", "Product_Code", "FY", "WeekNbr"], how="left")

# Filling missing values with zero
bronze_full[["PACKS", "Shipments", "aPounds"]] = bronze_full[["PACKS", "Shipments", "aPounds"]].fillna(0)

# Saving Final dataset
bronze_full.to_csv("bronze_kpi_weekly_final.csv", index=False)

bronze_full.sample(10)

bronze_full.shape

"""# Lane Harmonization – Before vs After"""

import matplotlib.pyplot as plt

# BEFORE (original Aug Lane column)
before_counts = aug["Lane"].value_counts().sort_index()

plt.figure()
before_counts.plot(kind="bar")
plt.title("Lane Distribution Before Harmonization")
plt.xlabel("Lane")
plt.ylabel("Record Count")
plt.xticks(rotation=45)
plt.show()

# AFTER (Harmonized Dest_Lane in Bronze)
after_counts = bronze_kpi["Dest_Lane"].value_counts().sort_index()

plt.figure()
after_counts.plot(kind="bar")
plt.title("Lane Distribution After Harmonization")
plt.xlabel("Dest_Lane")
plt.ylabel("Record Count")
plt.xticks(rotation=45)
plt.show()

"""# Weekly Volume Trend by Lane"""

weekly_lane = bronze_full.groupby(["WeekNbr", "Dest_Lane"])["aPounds"].sum().unstack()

plt.figure()
weekly_lane.plot()
plt.title("Weekly Weight Trend by Destination Lane")
plt.xlabel("WeekNbr")
plt.ylabel("Total aPounds")
plt.legend(title="Dest_Lane")
plt.show()

